channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - accelerate==1.12.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.4.2
  - scipy==1.15.3
  - torch==2.9.1
  - transformers==4.57.6
name: mlflow-env
